language: php

php:
  - 7.1
  - hhvm

sudo: false

addons:
    apt_packages:
        - parallel

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.* COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.1
      env: SYMFONY_VERSION=3.3.* DEPS=dev
    - php: 7.0
      env: SYMFONY_VERSION=3.1.*
  fast_finish: true

git:
    depth: 1

env:
    global:
        - MIN_PHP=5.5.9
        - SYMFONY_PROCESS_PHP_TEST_BINARY=~/.phpenv/versions/5.6/bin/php
cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit
        - php-$MIN_PHP

before_install:
    - |
      # General configuration
      stty cols 120
      PHP=$TRAVIS_PHP_VERSION
      [ -d ~/.composer ] || mkdir ~/.composer
      cp .composer/* ~/.composer/
      export PHPUNIT=$(readlink -f ./phpunit)
      export PHPUNIT_X="$PHPUNIT --exclude-group tty,benchmark,intl-data"
      export COMPOSER_UP='composer update --no-progress --no-suggest --ansi'

      # tfold is a helper to create folded reports
      tfold () {
          title=$1
          fold=$(echo $title | sed -r 's/[^-_A-Za-z\d]+/./g')
          shift
          echo -e "travis_fold:start:$fold\\n\\e[1;34m$title\\e[0m"
          bash -xc "$*" 2>&1 &&
              echo -e "\\e[32mOK\\e[0m $title\\n\\ntravis_fold:end:$fold" ||
              ( echo -e "\\e[41mKO\\e[0m $title\\n" && exit 1 )
      }
      export -f tfold

      # php.ini configuration
      if [[ $PHP = hhvm* ]]; then
          INI=/etc/hhvm/php.ini
      else
          INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
          phpenv config-rm xdebug.ini || echo "xdebug not available"
      fi
      echo date.timezone = Europe/Paris >> $INI
      echo memory_limit = -1 >> $INI
      echo session.gc_probability = 0 >> $INI
      echo opcache.enable_cli = 1 >> $INI
      echo hhvm.jit = 0 >> $INI
      echo apc.enable_cli = 1 >> $INI
      echo extension = redis.so >> $INI
      echo extension = memcached.so >> $INI
      export COMPOSER_ROOT_VERSION=$SYMFONY_VERSION.x-dev
      [[ $PHP = 5.* ]] && echo extension = memcache.so >> $INI
      if [[ $PHP = 5.* ]]; then
          echo extension = mongo.so >> $INI
      elif [[ $PHP = 7.* ]]; then
          echo extension = mongodb.so >> $INI
      fi

      # Matrix lines for intermediate PHP versions are skipped for pull requests
      if [[ ! $deps && ! $PHP = ${MIN_PHP%.*} && $TRAVIS_PULL_REQUEST != false ]]; then
          deps=skip
          skip=1
      else
          COMPONENTS=$(find src -mindepth 3 -type f -name phpunit.xml.dist -printf '%h\n')
      fi
      if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
      phpenv config-rm xdebug.ini || true

install:
    - |
      # Create local composer packages for each patched components and reference them in composer.json files when cross-testing components
      if [[ ! $skip ]]; then
          export SYMFONY_DEPRECATIONS_HELPER=weak &&
          cp composer.json composer.json.orig &&
          echo -e '{\n"require":{'"$(grep phpunit-bridge composer.json)"'"php":"*"},"minimum-stability":"dev"}' > composer.json &&
          php .github/build-packages.php HEAD^ $COMPONENTS &&
          mv composer.json composer.json.phpunit &&
          mv composer.json.orig composer.json
      fi

    - |
      composer self-update
      if [ "$DEPS" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi
      if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi
      if [[ ! $skip ]]; then $COMPOSER_UP; fi
      if [[ ! $skip ]]; then ./phpunit install; fi
      # phpinfo
      if [[ ! $PHP = hhvm* ]]; then php -i; else hhvm --php -r 'print_r($_SERVER);print_r(ini_get_all());'; fi

    - |
      run_tests () {
          set -e
          if [[ $skip ]]; then
              echo -e "\\n\\e[1;34mIntermediate PHP version $PHP is skipped for pull requests.\\e[0m"
          elif [[ $deps = high ]]; then
              echo "$COMPONENTS" | parallel --gnu -j10% "tfold {} 'cd {} && $COMPOSER_UP && $PHPUNIT_X$LEGACY'"
          elif [[ $deps = low ]]; then
              echo "$COMPONENTS" | parallel --gnu -j10% "tfold {} 'cd {} && $COMPOSER_UP --prefer-lowest --prefer-stable && $PHPUNIT_X'"
          elif [[ $PHP = hhvm* ]]; then
              $PHPUNIT --exclude-group benchmark,intl-data
          else
              echo "$COMPONENTS" | parallel --gnu -j10% "tfold {} 'cd {} && $COMPOSER_UP && $PHPUNIT_X {}"
              tfold tty-group $PHPUNIT --group tty
          fi
      }

script:
    - (run_tests)

notifications:
  irc: "irc.freenode.org#symfony-cmf"
