language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
  - SYMFONY_VERSION=2.3.*

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.2.*
    - php: 5.5
      env: SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/routing:${SYMFONY_VERSION} --prefer-source

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
