language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

env:
  matrix: SYMFONY_VERSION=3.2.*
  global:
    - SYMFONY_DEPRECATIONS_HELPER=42
    - SYMFONY_PHPUNIT_DIR=.phpunit SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
    - SYMFONY_PHPUNIT_VERSION=5.7

matrix:
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_VERSION=2.8.* SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.1
      env: DEPS=dev SYMFONY_VERSION=3.3.*
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*
    - php: hhvm
      dist: trusty
  fast_finish: true

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - if [ "$DEPS" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi

install: composer update --prefer-dist $COMPOSER_FLAGS

script: vendor/bin/simple-phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
