language: php
php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.1
      env: STABILITY=dev
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: hhvm
      dist: trusty
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - ${STABILITY:+ composer config 'minimum-stability' "$STABILITY"}

install: composer update --prefer-dist $COMPOSER_FLAGS

before_script: vendor/bin/phpunit --version

script: vendor/bin/phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
