language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
 
env:
  - SYMFONY_VERSION=no

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.3.*
    - php: 5.5
      env: SYMFONY_VERSION=2.4.*
    - php: 5.5
      env: SYMFONY_VERSION=2.6.*

before_script:
  - composer self-update
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;' 
  - sh -c 'if [ "$SYMFONY_VERSION" != "no" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi;'
  - composer update --prefer-dist
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
