language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
     - SYMFONY_PHPUNIT_DIR=.phpunit SYMFONY_PHPUNIT_REMOVE="symfony/yaml" SYMFONY_PHPUNIT_VERSION=5.7

matrix:
  include:
    - php: hhvm
      dist: trusty

sudo: false

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  
install: composer update --prefer-dist

script: vendor/bin/simple-phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
